### ISSUE TITLE
Fcitx modifies the X11 selection in QtWebEngine applications

### ISSUE THREAD

**Issue by LiteracyFanatic** [fcitx/fcitx-qt5#38]
Using `fcitx` with `QtWebEngine` applications like `qutebrowser` or `falkon` seems to modify the X11 selection on Linux. This is undesirable because I have scripts that trigger on selection change which I don't want `fcitx` to trigger. Is the X11 selection manipulation intentional, or just something that Qt is doing automatically? Any insights would be appreciated.

**Comment by wengxt** [comment]
Fcitx never modifies primary/clipboard because there is no code doing such a thing in fcitx.

Sounds like a historical chrome bug that I reported to chrome long time ago, it should already be fixed within chrome years ago, but consider webengine is a port so it is possible for some reason the bug shown up during the port.

You can take a look and report the bug to Qt.

https://bugs.chromium.org/p/chromium/issues/detail?id=113805

**Comment by LiteracyFanatic** [comment]
Ok, thanks for the information. Actually, I just tested it and the same issue occurs for me in the most recent version of chrome as well. Strange.

**Comment by wengxt** [comment]
then likely this is broken in some new chrome version, might need to reopen
that bug in chrome instead of file a bug to qt.

**Comment by LiteracyFanatic** [comment]
I'll do that. Thanks.
